### ISSUE TITLE
Saving uboot env to persistent storage does not work on qemuarm64?

### ISSUE THREAD

**Issue by liuming50** [foundriesio/meta-lmp#186]
We have /mnt/boot/uboot.env set in:

https://github.com/foundriesio/meta-lmp/blob/e9714602dd860a7911321de4da2824e450a2b23d/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/qemuarm64/fw_env.config#L1

but how could this work without setting:

CONFIG_ENV_IS_IN_EXT4 or CONFIG_ENV_IS_IN_FAT in qemu_arm64_defconfig of:
https://github.com/foundriesio/u-boot/tree/2019.10+fio/ ?

**Comment by mike-scott** [comment]
@liuming50 Hello!
The change you are referring to is here:
https://github.com/foundriesio/meta-lmp/blob/master/meta-lmp-bsp/recipes-bsp/u-boot/u-boot-fio/qemuarm64/lmp.cfg#L4

**Comment by liuming50** [comment]
Arha, thanks a lot, did not notice that file.
