### ISSUE TITLE
New override syntax

### ISSUE THREAD

**Issue by sergioprado** [foundriesio/meta-lmp#485]
Any plans to move the master branch to the new override syntax?

**Comment by ricardosalveti** [comment]
https://github.com/foundriesio/meta-lmp/tree/master-next is already using the new syntax (and honister compatibile), we're just working on making it stable at the moment and will release with it.

Just be aware that master-next is current a rebase-based branch.

**Comment by sergioprado** [comment]
Perfect, thanks!
