### ISSUE TITLE
lmp-device-register: Adding support for new tags and docker-app flags

### ISSUE THREAD

**Issue by doanac** [foundriesio/meta-lmp#57]
The newest version of lmp-device-register includes optional support for `--tags` and `--docker-apps`. I'm not sure the best way to include this. 

Maybe by changing:
https://github.com/foundriesio/meta-lmp/blob/27134dfa99b6397cf1eff802af4c91a81a26954f/recipes-sota/lmp-device-register/lmp-device-register_git.bb#L18

to something like
~~~
EXTRA_OECMAKE += "\
    ${@oe.utils.conditional('SOTA_CLIENT', 'aktualizr-lite', '-DDEVICE_API=https://api.foundries.io/ota/devices/ -DAKLITE_TAGS=1', '', d)} \
"
~~~
We also need a `-DDOCKER_APPS=1`. I guess we could throw that in the same line also. But its technically tied to whether or not this is enabled:
 https://github.com/foundriesio/meta-lmp/blob/27134dfa99b6397cf1eff802af4c91a81a26954f/recipes-sota/aktualizr/aktualizr_%25.bbappend#L23

**Comment by ricardosalveti** [comment]
It is fine to always have docker_apps enabled (-DDOCKER_APPS=1), so I was wondering if we should simply just enable AKLITE_TAGS by default as well.

In this case I'm usually prefer having it enable by default and allowing the user to disable if needed, an not the other way around. What do you think?

**Comment by doanac** [comment]
That sounds fine.
